[package]
name = "ash"
version = "0.2.0"
authors = ["maik klein <maikklein@googlemail.com>"]
description = "Vulkan bindings for Rust"
license = "MIT"
repository = "https://github.com/MaikKlein/ash"
readme = "README.md"
keywords = ["vulkan", "graphic"]
documentation = "https://docs.rs/ash"

[dependencies]
shared_library = "0.1.5"
sharedlib = "6.0.0"
lazy_static = "0.2.1"
