[package]
name = "example"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]
glfw = "0.9.1"
vk_loader = { version = "0.1.0", path = "../vk_loader"}
vk_loader2 = { version = "0.1.0", path = "../vk_loader2"}
ash = { version = "0.1.0", path = "../ash"}
owning_ref = "0.2.0"
bitflags = "0.7.0"
