[package]
name = "example"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]
glfw = "0.9.1"
vk_loader = { version = "0.1.0", path = "../vk_loader"}
ash = { version = "0.1.0", path = "../ash"}
