[package]
name = "examples"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]
winit = "0.5.6"
image = "0.10.4"
ash = { path = "../ash" }

[target.'cfg(windows)'.dependencies]
user32-sys = "0.2.0"
winapi = "0.2.8"
