[package]
name = "ash"
version = "0.1.0"
authors = ["maik klein <maikklein@googlemail.com>"]

[dependencies]
lazy_static = "0.2.1"
shared_library = "0.1.5"
glfw = "0.9.1"
bitflags = "0.7.0"

vk_loader = { version = "0.1.0", path = "../vk_loader"}
vk_loader2 = { version = "0.1.0", path = "../vk_loader2"}
