[package]
name = "ash"
version = "0.29.0"
authors = ["maik klein <maikklein@googlemail.com>"]
description = "Vulkan bindings for Rust"
license = "MIT"
repository = "https://github.com/MaikKlein/ash"
readme = "../README.md"
keywords = ["vulkan", "graphic"]
documentation = "https://docs.rs/ash"
edition = "2018"

[dependencies]
libloading = "0.5.2"

[features]
default = []

[package.metadata.release]
no-dev-version = true
